apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-hpa
  namespace: psi5120-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-hpa
  template:
    metadata:
      labels:
        app: web-hpa
    spec:
      containers:
        - name: web
          # Imagem imutável publicada no ECR para o experimento EKS.
          image: 103942587929.dkr.ecr.sa-east-1.amazonaws.com/psi5120-hpa-web:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
